language: python
python:
  - "3.8"

# command to install dependencies
install:
  - wget --quiet https://curl.haxx.se/ca/cacert.pem
  - export SSL_CERT_FILE=./cacert.pem
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment.yml 
  - conda info --envs
  - source activate braindecode
  - pip install sphinx-gallery
  - pip install sphinx_rtd_theme
  - pip install --upgrade pytest pytest-cov codecov
  - pip install --upgrade coloredlogs
  - pip install --upgrade pyyaml
  - pip install --upgrade git+https://github.com/NeuroTechX/moabb
  - pip install -e .

# command to run tests
script:
  - pytest --cov=braindecode test/
  # Use Sphinx to make the html docs
  # - cd docs; pip install -r requirements.txt; make html  # we build the doc on circleci now

after_script:
  # Need to run from source dir to execute "git" commands
  - codecov;
