name: braindecode
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
- python>=3.7
- numpy
- pandas
- scipy
- mkl
- matplotlib
- h5py
- pytorch
- pytest
- pip
- skorch
- mne
- pip:
  - https://github.com/braindecode/braindecode/zipball/master
