name: braindecode
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
- python==3.6
- numpy
- pandas
- scipy
- mkl
- matplotlib
- h5py
- pytorch
- pytest
- pip
- skorch==0.7
- mne
- pip:
  - https://github.com/braindecode/braindecode/zipball/master
