name: braindecode
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - scipy
  - mkl
  - matplotlib
  - h5py
  - pytorch
  - pytest
  - pip
  - skorch<0.14
  - joblib
  - memory_profiler
  - einops
  - pip:
      - mne
      - https://github.com/braindecode/braindecode/zipball/master
      - docstring_inheritance
